# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- manual

pool: ado_agent_rike

steps:
- task: TerraformTask@5
  displayName: Init Task
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    backendServiceArm: 'svc-rike'
    backendAzureRmOverrideSubscriptionID: '5b9f49a3-8bda-49fa-88c0-baf31ef2f4f3'
    backendAzureRmResourceGroupName: 'rike-rg-1'
    backendAzureRmStorageAccountName: 'rikestorage13'
    backendAzureRmContainerName: 'pipedrum'
    backendAzureRmKey: 'pipedrum.tfstate'
- task: TerraformTask@5
  displayName: Plan task
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    environmentServiceNameAzureRM: 'svc-rike'
